# Classification Neural Net - NUMPY

In this notebook I will develop a simple classification neural network from scratch using pythons NUMPY, instead of relying on libaries like pytorch.

In [46]:
import numpy as np
import pandas as pd

First we will define the constants that will be used throughout the notebook.

In [47]:
bias = 0
learning_rate = 0.1
truth = 1 # the value we expect (the actual value that's labeled )

Next, lets create some sample data to work with.
- features: is (n_samples, n_features)
- labels: is (n_samples, 1)


In [48]:
np.random.seed(42)
n_samples = 8
n_features = 3
features_matrix = np.random.rand(n_samples, n_features)
labels = np.array([[0], [1], [0], [1], [0], [1], [0], [1]])
weights_matrix = np.random.randn(n_features, 4)
print(f"X shape: {features_matrix.shape}")
print(features_matrix)
print(f"y shape: {labels.shape}")
print(labels)

X shape: (8, 3)
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]]
y shape: (8, 1)
[[0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]]


### Neural Network Forward Pass – 1 Hidden Layer (NumPy variable names)

We will create functions for each part of the forward pass:
1. **Hidden layer linear transformation** – multiply the feature matrix by the weight matrix, add bias, and produce the pre-activation values for the hidden layer.
2. **Hidden layer activation (ReLU)** – introduce non-linearity so the network can learn complex patterns.
3. **Output layer linear transformation** – take the hidden layer activations, multiply by the output layer weights, add bias, and produce the output logits.
4. **Output layer activation (Sigmoid)** – squash the logits into the range (0, 1) to get probabilities.
5. **Loss (MSE)** – measure how far the predicted values are from the target labels.

---

#### 1. Hidden layer linear transformation
$$
Z1 = \text{features\_matrix} \cdot \text{weights\_matrix} + \text{bias}
$$

Where:
- `features_matrix` = input data `(n_samples, n_features)`
- `weights_matrix` = hidden layer weights `(n_features, n_hidden)`
- `bias` = hidden layer bias `(1, n_hidden)`

---

#### 2. Hidden layer activation (ReLU)
$$
A1 = \max(0, Z1)
$$

Where:
- `A1` = hidden layer activation output `(n_samples, n_hidden)`

---

#### 3. Output layer linear transformation
$$
Z2 = A1 \cdot W2 + b2
$$

Where:
- `W2` = output layer weights `(n_hidden, 1)`
- `b2` = output layer bias `(1, 1)`

---

#### 4. Output layer activation (Sigmoid)
$$
y_{\text{pred}} = \frac{1}{1 + e^{-Z2}}
$$

Where:
- `y_pred` = predicted probabilities `(n_samples, 1)`

---

#### 5. Mean Squared Error (MSE) Loss
$$
\text{loss} = \frac{1}{n_{\text{samples}}} \sum_{i=1}^{n_{\text{samples}}} \left( y_{\text{pred}_i} - y_i \right)^2
$$

Where:
- `y` = true labels `(n_samples, 1)`


In [49]:
def hidden_layer_output_transformation(features_matrix, weights_matrix, bias):
    output_matrix = features_matrix @ weights_matrix + bias
    return output_matrix

def hidden_ReLU_activation():
    print("hidden layer activation")

def output_layer_transformation():
    print("output layer")

def output_sigmoid_activation():
    print("output sigmoid activation")

def MSE_loss():
    print("MSE_loss")

hidden_layer_output = hidden_layer_output_transformation(features_matrix, weights_matrix, bias)
print(hidden_layer_output)

[[-0.40827206 -0.19262465 -1.50941963  1.17941254]
 [ 0.69879287 -0.16335953 -0.23301305 -0.50537645]
 [-0.74745409 -0.09237689 -1.35473578  1.35609836]
 [ 0.44401448 -0.44049936 -0.55947892  0.79545129]
 [ 0.99526368 -0.21742982 -0.29759288 -0.76945534]
 [-0.21200664 -0.16072923 -0.65354531  0.82499286]
 [ 0.10703705 -0.24369272 -0.67419033  0.6273231 ]
 [-0.17464059 -0.10595443 -0.54727919  0.58961859]]
